### PR TITLE
build Release configuration and fix compiler versions

### LINKED ISSUE #211: Cuda PTX Error with RTX3090 on windows.
Trying to run v24.0.1 (installed from anaconda) via CIL I get an error:

`Error: C:\Users\ofn77899\Dev\CCPi-Regularisation-Toolkit\src\Core\regularisers_GPU\TV_FGP_GPU_core.cu:408, code: 222, reason: the provided PTX was compiled with an unsupported toolchain.`

This is on a windows, with an RTX3090 and driver version 546.01

@paskino how did you build the binaries? Which version of CUDA Toolkit did you use?

### PR DESCRIPTION
**Pull request by gfardell**
Sets the correct compiler and toolkit to be used by the build.  

Builds the shared library as 'RelWithDebInfo'. Previous build was defaulting to `Debug` as `DCMAKE_BUILD_TYPE` is not used by MSVC.

closes #211

### CODE REVIEW

**Review by casperdcl — APPROVED** [review]

**Review by casperdcl — CHANGES_REQUESTED** [review]
I think you may have to use CRLF line endings since it's a batch file.

**Comment by gfardell** [comment]
> I think you may have to use CRLF line endings since it's a batch file.

odd... I edited and pushed from windows

**Comment by gfardell** [comment]
PS C:\Users\[USER]\GitHub\CCPi-Regularisation-Toolkit\recipe> git ls-files --eol
i/crlf  w/crlf  attr/                   bld.bat
i/lf    w/crlf  attr/                   build.sh
i/lf    w/crlf  attr/                   conda_build_config.yaml
i/lf    w/crlf  attr/                   meta.yaml

**Comment by casperdcl** [comment]
that's only after my latest commit :)

**Review by casperdcl — APPROVED** [review]

**Pull request merged**
